sudo: false
language: python
python:
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
    dist: xenial
    sudo: true
insatll:
  - pip install poetry
  - poetry install -vvv
script:
  - poetry run coverage run --source=APITEST -m pytest -v
  - poetry run coverage report -m
after_success:
  - poetry run coveralls